message("LAWA State and Trend analysis started")
print(Sys.time())
timeAtStart<- Sys.time()
source("//file/herman/r/oa/08/02/2015/Water Quality/RScript/lawa_state/lawa_state_5yr.R")
source("//file/herman/r/oa/08/02/2015/Water Quality/RScript/lawa_state/lawa_trend_5yr.R")
source("//file/herman/r/oa/08/02/2015/Water Quality/RScript/lawa_state/lawa_trend_10yr.R")
source("//file/herman/r/oa/08/02/2015/Water Quality/RScript/lawa_state/FinaliseTrend.R")
source("//file/herman/r/oa/08/02/2015/Water Quality/RScript/lawa_state/PackageDataForDelivery.R")
message("Process finished")
print(Sys.time())
print(Sys.time()-timeAtStart)